---

- hosts: all
  vars:
    sudo: no
    nopasswd: no
  vars_prompt:
    - name: username
      prompt: Input new username
      private: no
      when: username is undefined

    - name: identity_file
      prompt: Input path of public identity file
      private: no
      default: "~/.ssh/id_rsa.pub"
      when: identity_file is undefined

  tasks:
    - include: roles/users/tasks/user_creation.yml
    - include: roles/users/tasks/ssh_copy_id.yml
    - include: roles/users/tasks/set_nopasswd_attribute_to_group.yml groupname=nopasswd
      when: (nopasswd)

