---

- hosts: all
  vars:
    sudo: false
    nopasswd: false
  vars_prompt:
    - name: username
      prompt: Input new username
      private: false
      when: username is undefined

    - name: identity_file
      prompt: Input path of public identity file
      private: false
      default: "~/.ssh/id_rsa.pub"
      when: identity_file is undefined

  tasks:
    - import_tasks: roles/users/tasks/user_creation.yml
    - import_tasks: roles/users/tasks/ssh_copy_id.yml
    - import_tasks: roles/users/tasks/set_nopasswd_attribute_to_group.yml groupname=nopasswd
      when: nopasswd
    - import_tasks: roles/users/tasks/append_user_to_group.yml groupname=nopasswd
      when: nopasswd
